import { Vehicle } from "./types";

export const AUTOEXITO_INVENTORY: Vehicle[] = [
  {
    "Año": "2024",
    "Marca": "Hyundai",
    "Modelo": "Elantra",
    "Sub-Modelo/Trim Level": "SEL",
    "Motor/hp": "2.0L 4 Cilindros / 147 hp",
    "Transmisión": "Automática IVT",
    "MPG": "31/40",
    "Color": "Blanco",
    "Precio": "$21,995",
    "Millaje": "12,450",
    "FotoWeblink": "https://autoexitopr.com/wp-content/uploads/2026/08/DSC_1371-1170x500.jpg",
    "Clase": "Sedán",
    "Carroceria": "Sedán",
    "Descripcion": "Hyundai Elantra 2024 en impecable estado con moderna cabina digital, alta eficiencia de combustible hasta 40 MPG y garantías vigentes.",
    "Disponibles": "Disponible",
    "Municipio": "Vega Alta",
    "Dealer": "Auto Exito Imports"
  },
  {
    "Año": "2023",
    "Marca": "Chevrolet",
    "Modelo": "Blazer",
    "Sub-Modelo/Trim Level": "LT AWD",
    "Motor/hp": "2.0L Turbo / 228 hp",
    "Transmisión": "9 Velocidades Automática",
    "MPG": "22/27",
    "Color": "Rojo",
    "Precio": "$28,995",
    "Millaje": "24,800",
    "FotoWeblink": "https://autoexitopr.com/wp-content/uploads/2026/08/DSC_1331-1170x500.jpg",
    "Clase": "SUV",
    "Carroceria": "SUV",
    "Descripcion": "Chevrolet Blazer 2023 estilo deportivo con tracción AWD, pantalla táctil grande, rines deportivos y amplio espacio de carga.",
    "Disponibles": "Disponible",
    "Municipio": "Vega Alta",
    "Dealer": "Auto Exito Imports"
  },
  {
    "Año": "2025",
    "Marca": "Hyundai",
    "Modelo": "Santa Fe",
    "Sub-Modelo/Trim Level": "Calligraphy / XRT",
    "Motor/hp": "2.5L Turbo / 277 hp",
    "Transmisión": "8 Velocidades Doble Embrague",
    "MPG": "20/28",
    "Color": "Verde / Cemento",
    "Precio": "$38,995",
    "Millaje": "5,100",
    "FotoWeblink": "https://autoexitopr.com/wp-content/uploads/2026/08/DSC_1324-1170x500.jpg",
    "Clase": "SUV",
    "Carroceria": "SUV",
    "Descripcion": "Nueva Hyundai Santa Fe 2025 de última generación con diseño robusto, 3 filas de asientos, doble pantalla curva y asistencia al conductor.",
    "Disponibles": "Disponible",
    "Municipio": "Vega Alta",
    "Dealer": "Auto Exito Imports"
  },
  {
    "Año": "2022",
    "Marca": "Ford",
    "Modelo": "Bronco",
    "Sub-Modelo/Trim Level": "Big Bend 4x4",
    "Motor/hp": "2.3L EcoBoost Turbo / 300 hp",
    "Transmisión": "10 Velocidades Automática 4WD",
    "MPG": "20/22",
    "Color": "Azul / Negro",
    "Precio": "$41,995",
    "Millaje": "28,300",
    "FotoWeblink": "https://autoexitopr.com/wp-content/uploads/2025/11/WhatsApp-Image-2025-11-26-at-14.03.18-1170x500.jpeg",
    "Clase": "SUV",
    "Carroceria": "SUV",
    "Descripcion": "Ford Bronco Big Bend 2022 4x4 todoterreno con modos G.O.A.T., techo removible, aros todoterreno y óptimas condiciones en Puerto Rico.",
    "Disponibles": "Disponible",
    "Municipio": "Vega Alta",
    "Dealer": "Auto Exito Imports"
  },
  {
    "Año": "2023",
    "Marca": "Jeep",
    "Modelo": "Wrangler",
    "Sub-Modelo/Trim Level": "Unlimited Sahara 4x4",
    "Motor/hp": "3.6L V6 Pentastar / 285 hp",
    "Transmisión": "8 Velocidades Automática 4WD",
    "MPG": "19/24",
    "Color": "Blanco / Negro",
    "Precio": "$36,995",
    "Millaje": "21,500",
    "FotoWeblink": "https://autoexitopr.com/wp-content/uploads/2025/11/WhatsApp-Image-2025-11-14-at-13.46.17-1170x500.jpeg",
    "Clase": "SUV",
    "Carroceria": "SUV",
    "Descripcion": "Jeep Wrangler Unlimited 2023 4 puertas con tracción 4x4, interiores en piel, pantalla Uconnect, lista para la playa o la montaña.",
    "Disponibles": "Disponible",
    "Municipio": "Vega Alta",
    "Dealer": "Auto Exito Imports"
  },
  {
    "Año": "2024",
    "Marca": "Toyota",
    "Modelo": "Tacoma",
    "Sub-Modelo/Trim Level": "TRD Sport 4x4",
    "Motor/hp": "2.4L Turbo i-FORCE / 278 hp",
    "Transmisión": "8 Velocidades Automática",
    "MPG": "20/24",
    "Color": "Gris Subterráneo",
    "Precio": "$43,995",
    "Millaje": "11,200",
    "FotoWeblink": "https://autoexitopr.com/wp-content/uploads/2025/11/WhatsApp-Image-2025-10-27-at-16.50.34-1-1170x500.jpeg",
    "Clase": "Pickup",
    "Carroceria": "Pickup",
    "Descripcion": "Nueva Generación Toyota Tacoma TRD Sport 2024 con motor i-FORCE Turbo, suspensión TRD afinada, pantalla táctil de 14 pulgadas y tecnología Toyota Safety Sense 3.0.",
    "Disponibles": "Disponible",
    "Municipio": "Vega Alta",
    "Dealer": "Auto Exito Imports"
  },
  {
    "Año": "2025",
    "Marca": "Toyota",
    "Modelo": "Corolla",
    "Sub-Modelo/Trim Level": "LE Premium",
    "Motor/hp": "2.0L Dynamic Force / 169 hp",
    "Transmisión": "Automática CVT",
    "MPG": "32/41",
    "Color": "Plata",
    "Precio": "$23,995",
    "Millaje": "3,400",
    "FotoWeblink": "https://autoexitopr.com/wp-content/uploads/2025/10/WhatsApp-Image-2025-10-23-at-13.00.48-1170x500.jpeg",
    "Clase": "Sedán",
    "Carroceria": "Sedán",
    "Descripcion": "Toyota Corolla 2025 como nuevo con solo 3,400 millas, súper económico en consumo de combustible hasta 41 MPG y garantía de fábrica.",
    "Disponibles": "Disponible",
    "Municipio": "Vega Alta",
    "Dealer": "Auto Exito Imports"
  },
  {
    "Año": "2025",
    "Marca": "Toyota",
    "Modelo": "Corolla",
    "Sub-Modelo/Trim Level": "SE Sport",
    "Motor/hp": "2.0L Dynamic Force / 169 hp",
    "Transmisión": "Automática CVT con Paddle Shifters",
    "MPG": "31/40",
    "Color": "Blanco Perlado",
    "Precio": "$24,995",
    "Millaje": "4,200",
    "FotoWeblink": "https://autoexitopr.com/wp-content/uploads/2025/10/WhatsApp-Image-2025-10-23-at-13.00.48-2-1170x500.jpeg",
    "Clase": "Sedán",
    "Carroceria": "Sedán",
    "Descripcion": "Toyota Corolla SE 2025 edición deportiva con aros de aleación bitono, spoiler trasero, asientos deportivos y suspensión calibrada.",
    "Disponibles": "Disponible",
    "Municipio": "Vega Alta",
    "Dealer": "Auto Exito Imports"
  },
  {
    "Año": "2023",
    "Marca": "Nissan",
    "Modelo": "Kicks",
    "Sub-Modelo/Trim Level": "SV",
    "Motor/hp": "1.6L 4 Cilindros / 122 hp",
    "Transmisión": "Automática Xtronic CVT",
    "MPG": "31/36",
    "Color": "Gris / Techo Negro",
    "Precio": "$19,995",
    "Millaje": "22,400",
    "FotoWeblink": "https://autoexitopr.com/wp-content/uploads/2025/09/WhatsApp-Image-2025-09-29-at-15.23.06-1170x500.jpeg",
    "Clase": "SUV",
    "Carroceria": "SUV",
    "Descripcion": "Nissan Kicks SV 2023 crossover compacto y ágil, perfecto para la ciudad con cámara de reversa, Apple CarPlay, Android Auto y excelente rendimiento.",
    "Disponibles": "Disponible",
    "Municipio": "Vega Alta",
    "Dealer": "Auto Exito Imports"
  },
  {
    "Año": "2023",
    "Marca": "Mitsubishi",
    "Modelo": "Outlander",
    "Sub-Modelo/Trim Level": "SE 3 Filas",
    "Motor/hp": "2.5L 4 Cilindros / 181 hp",
    "Transmisión": "Automática CVT",
    "MPG": "24/31",
    "Color": "Blanco Diamante",
    "Precio": "$25,995",
    "Millaje": "27,600",
    "FotoWeblink": "https://autoexitopr.com/wp-content/uploads/2025/09/WhatsApp-Image-2025-09-29-at-15.24.28-1170x500.jpeg",
    "Clase": "SUV",
    "Carroceria": "SUV",
    "Descripcion": "Mitsubishi Outlander 2023 con 3 filas de asientos para 7 pasajeros, techo panorámico, llave inteligente y gran versatilidad para la familia.",
    "Disponibles": "Disponible",
    "Municipio": "Vega Alta",
    "Dealer": "Auto Exito Imports"
  },
  {
    "Año": "2025",
    "Marca": "Hyundai",
    "Modelo": "Elantra",
    "Sub-Modelo/Trim Level": "Limited",
    "Motor/hp": "2.0L 4 Cilindros / 147 hp",
    "Transmisión": "Automática Smartstream IVT",
    "MPG": "31/40",
    "Color": "Gris Cemento",
    "Precio": "$23,495",
    "Millaje": "2,900",
    "FotoWeblink": "https://autoexitopr.com/wp-content/uploads/2025/09/WhatsApp-Image-2025-09-29-at-13.13.06-1170x500.jpeg",
    "Clase": "Sedán",
    "Carroceria": "Sedán",
    "Descripcion": "Hyundai Elantra 2025 Limited casi nuevo con interiores en piel, sonido premium Bose, navegación integrada y asistencias avanzadas de carril.",
    "Disponibles": "Disponible",
    "Municipio": "Vega Alta",
    "Dealer": "Auto Exito Imports"
  },
  {
    "Año": "2024",
    "Marca": "Hyundai",
    "Modelo": "Elantra",
    "Sub-Modelo/Trim Level": "N-Line",
    "Motor/hp": "1.6L Turbo GDI / 201 hp",
    "Transmisión": "7 Velocidades Doble Embrague",
    "MPG": "28/35",
    "Color": "Negro Fantasma",
    "Precio": "$24,995",
    "Millaje": "14,300",
    "FotoWeblink": "https://autoexitopr.com/wp-content/uploads/2025/09/WhatsApp-Image-2025-09-29-at-13.13.05-2-1170x500.jpeg",
    "Clase": "Sedán",
    "Carroceria": "Sedán",
    "Descripcion": "Hyundai Elantra N-Line 2024 con motor Turbo de 201 HP, escape deportivo, suspensión independiente multienlace y detalles N deportivos.",
    "Disponibles": "Disponible",
    "Municipio": "Vega Alta",
    "Dealer": "Auto Exito Imports"
  },
  {
    "Año": "2024",
    "Marca": "Mitsubishi",
    "Modelo": "Outlander",
    "Sub-Modelo/Trim Level": "SEL Super All-Wheel Control",
    "Motor/hp": "2.5L 4 Cilindros / 181 hp",
    "Transmisión": "Automática CVT AWD",
    "MPG": "24/30",
    "Color": "Gris Titanio",
    "Precio": "$27,995",
    "Millaje": "15,800",
    "FotoWeblink": "https://autoexitopr.com/wp-content/uploads/2025/09/WhatsApp-Image-2025-09-29-at-13.13.05-1-1170x500.jpeg",
    "Clase": "SUV",
    "Carroceria": "SUV",
    "Descripcion": "Mitsubishi Outlander SEL 2024 con tracción integral S-AWC, asientos en piel acolchada, compuerta trasera eléctrica y 3 filas de asientos.",
    "Disponibles": "Disponible",
    "Municipio": "Vega Alta",
    "Dealer": "Auto Exito Imports"
  },
  {
    "Año": "2023",
    "Marca": "Toyota",
    "Modelo": "Corolla",
    "Sub-Modelo/Trim Level": "LE",
    "Motor/hp": "2.0L 4 Cilindros / 169 hp",
    "Transmisión": "Automática CVT",
    "MPG": "32/41",
    "Color": "Plata",
    "Precio": "$20,995",
    "Millaje": "29,400",
    "FotoWeblink": "https://autoexitopr.com/wp-content/uploads/2025/09/WhatsApp-Image-2025-09-06-at-16.58.42-1170x500.jpeg",
    "Clase": "Sedán",
    "Carroceria": "Sedán",
    "Descripcion": "Toyota Corolla LE 2023 con motor 2.0L más potente y eficiente, pantalla de 8 pulgadas, control crucero adaptativo y confiabilidad legendaria.",
    "Disponibles": "Disponible",
    "Municipio": "Vega Alta",
    "Dealer": "Auto Exito Imports"
  },
  {
    "Año": "2023",
    "Marca": "Kia",
    "Modelo": "Carnival",
    "Sub-Modelo/Trim Level": "LX",
    "Motor/hp": "3.5L V6 / 290 hp",
    "Transmisión": "8 Velocidades Automática",
    "MPG": "19/26",
    "Color": "Blanca",
    "Precio": "$29,995",
    "Millaje": "31,200",
    "FotoWeblink": "https://autoexitopr.com/wp-content/uploads/2025/09/WhatsApp-Image-2025-09-06-at-16.58.42-1-1170x500.jpeg",
    "Clase": "Minivan",
    "Carroceria": "Van Comercial",
    "Descripcion": "Kia Carnival LX 2023 vehículo multipropósito (MPV) con 8 pasajeros, puertas corredizas eléctricas, motor potente V6 y máximo confort familiar.",
    "Disponibles": "Disponible",
    "Municipio": "Vega Alta",
    "Dealer": "Auto Exito Imports"
  },
  {
    "Año": "2025",
    "Marca": "Kia",
    "Modelo": "Soul",
    "Sub-Modelo/Trim Level": "GT-Line",
    "Motor/hp": "2.0L 4 Cilindros / 147 hp",
    "Transmisión": "Automática Intelligent Variable",
    "MPG": "29/35",
    "Color": "Rojo / Techo Negro",
    "Precio": "$22,495",
    "Millaje": "4,800",
    "FotoWeblink": "https://autoexitopr.com/wp-content/uploads/2025/09/WhatsApp-Image-2025-09-29-at-13.12.01-1170x500.jpeg",
    "Clase": "Hatchback",
    "Carroceria": "Hatchback / Crossover",
    "Descripcion": "Kia Soul GT-Line 2025 nuevo diseño crossover urbano con volante deportivo en D, aros de 18 pulgadas, pantalla de 10.25 pulgadas con navegación.",
    "Disponibles": "Disponible",
    "Municipio": "Vega Alta",
    "Dealer": "Auto Exito Imports"
  },
  {
    "Año": "2023",
    "Marca": "Mazda",
    "Modelo": "CX-5",
    "Sub-Modelo/Trim Level": "2.5 S Select AWD",
    "Motor/hp": "2.5L Skyactiv-G / 187 hp",
    "Transmisión": "6 Velocidades Automática AWD",
    "MPG": "24/30",
    "Color": "Soul Red Crystal",
    "Precio": "$26,995",
    "Millaje": "23,100",
    "FotoWeblink": "https://autoexitopr.com/wp-content/uploads/2025/09/WhatsApp-Image-2025-09-06-at-16.58.40-1-1170x500.jpeg",
    "Clase": "SUV",
    "Carroceria": "SUV",
    "Descripcion": "Mazda CX-5 2023 con tracción i-Activ AWD estándar, acabados de lujo, asientos en piel sintética, color rojo insignia y manejo sumamente dinámico.",
    "Disponibles": "Disponible",
    "Municipio": "Vega Alta",
    "Dealer": "Auto Exito Imports"
  },
  {
    "Año": "2022",
    "Marca": "Hyundai",
    "Modelo": "Venue",
    "Sub-Modelo/Trim Level": "SEL",
    "Motor/hp": "1.6L 4 Cilindros / 121 hp",
    "Transmisión": "Automática Smartstream IVT",
    "MPG": "29/33",
    "Color": "Blanco",
    "Precio": "$17,995",
    "Millaje": "34,500",
    "FotoWeblink": "https://autoexitopr.com/wp-content/uploads/2025/05/WhatsApp-Image-2025-05-07-at-1.08.23-PM-1170x500.jpeg",
    "Clase": "SUV",
    "Carroceria": "SUV",
    "Descripcion": "Hyundai Venue SEL 2022 crossover compacto económico con techo corredizo, alerta de punto ciego, fácil de estacionar y pago mensual muy accesible.",
    "Disponibles": "Disponible",
    "Municipio": "Vega Alta",
    "Dealer": "Auto Exito Imports"
  },
  {
    "Año": "2023",
    "Marca": "Land Rover",
    "Modelo": "Range Rover Evoque",
    "Sub-Modelo/Trim Level": "R-Dynamic SE",
    "Motor/hp": "2.0L Turbocharged I4 / 246 hp",
    "Transmisión": "9 Velocidades Automática AWD",
    "MPG": "20/27",
    "Color": "Gris Carbón",
    "Precio": "$39,995",
    "Millaje": "19,200",
    "FotoWeblink": "https://autoexitopr.com/wp-content/uploads/2024/09/land-rover-2023-1-1148x500.jpg",
    "Clase": "De Lujo",
    "Carroceria": "SUV",
    "Descripcion": "Land Rover Range Rover Evoque 2023 de lujo británico con tracción AWD Terrain Response 2, asientos en piel Windsor, techo panorámico y audio Meridian.",
    "Disponibles": "Disponible",
    "Municipio": "Vega Alta",
    "Dealer": "Auto Exito Imports"
  },
  {
    "Año": "2023",
    "Marca": "Kia",
    "Modelo": "Rio",
    "Sub-Modelo/Trim Level": "S",
    "Motor/hp": "1.6L 4 Cilindros / 120 hp",
    "Transmisión": "Automática Intelligent Variable",
    "MPG": "32/41",
    "Color": "Azul",
    "Precio": "$16,995",
    "Millaje": "26,800",
    "FotoWeblink": "https://autoexitopr.com/wp-content/uploads/2024/08/P1000390EDIT-1148x500.jpg",
    "Clase": "Sedán",
    "Carroceria": "Sedán",
    "Descripcion": "Kia Rio S 2023 color azul eléctrico con pantalla táctil inalámbrica para Apple CarPlay / Android Auto, bajo millaje y rendimiento de hasta 41 MPG.",
    "Disponibles": "Disponible",
    "Municipio": "Vega Alta",
    "Dealer": "Auto Exito Imports"
  }
];
